"""empty message

Revision ID: 557300160016
Revises: 
Create Date: 2019-09-10 11:08:03.561154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557300160016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectname', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('auth_provider', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('family_name', sa.String(length=60), nullable=True),
    sa.Column('picture_url', sa.String(length=128), nullable=True),
    sa.Column('super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_family_name'), 'users', ['family_name'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_picture_url'), 'users', ['picture_url'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projectaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.String(length=256), nullable=True),
    sa.Column('accesslevel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectid'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samplerole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('samplename', sa.String(length=256), nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectid'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('samplename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samplerole')
    op.drop_table('projectaccess')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_picture_url'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_family_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
