"""empty message

Revision ID: 58bb066ccccb
Revises: ca6657ff65ec
Create Date: 2020-09-22 13:21:09.196327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bb066ccccb'
down_revision = 'ca6657ff65ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'exercise_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'exercise_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
