"""empty message

Revision ID: ca6657ff65ec
Revises: 557300160016
Create Date: 2020-09-22 12:23:47.435171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6657ff65ec'
down_revision = '557300160016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('exercise_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'exercise_mode')
    # ### end Alembic commands ###
